# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4daf85de3d66dd61466f74af0bec8b500e6bb58cd6daab6dc1c30ecd198414057ffbb90bceb168245a3a5e05361a483d2f77e845b692438f721048e3b2d289

test:
  secret_key_base: 7838ead9ae548bb0e42a4ac29372cb52a0f8777e7a71d84957e5eb3e12f8f004c320eb8427f8e0ec5ff2d90eaa8eb8d57989bbf90012a28c963a618fadd51bc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
